[tool.poetry]
name = "svaeva"
version = "0.1.0"
description = ""
authors = ["Vortex5Root"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
requests = "^2.31.0"
python-dotenv = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
